// Generated by CoffeeScript 1.9.2
(function() {
  var Q, _, allPromise, collection, p;

  Q = require('q');

  _ = require('underscore');

  p = function(data) {
    return Q.promise(function(resolve, reject) {
      if (data instanceof Object && !(data instanceof Array)) {
        return resolve(data);
      } else {
        return reject(new Error('data is not obj'));
      }
    });
  };

  collection = [
    {
      category: "可比克"
    }, {
      category: "乐事"
    }, {}
  ];

  allPromise = _.map(collection, function(v, i) {
    return p(v);
  });

  Q.all(allPromise).then(function(result) {
    return console.log(result);
  })["catch"](function(error) {
    return console.log(error);
  });

}).call(this);
