// Generated by CoffeeScript 1.9.1
(function() {
  var Q, _, allPromise, arr, collection, err, p;

  Q = require('q');

  _ = require('underscore');

  p = function(data) {
    return Q.promise(function(resolve, reject) {
      if (data instanceof Object && !(data instanceof Array)) {
        return resolve(data);
      } else {
        return reject(new Error('data is not obj'));
      }
    });
  };

  collection = [
    {
      category: "可比克"
    }, {
      category: "乐事"
    }, []
  ];

  allPromise = _.map(collection, function(v, i) {
    return p(v);
  });

  arr = [];

  err = [];

  Q.allSettled(allPromise).then(function(results) {
    results.forEach(function(v) {
      if (v.state === 'fulfilled') {
        return arr.push(v.value.category);
      } else {
        return err.push(v.reason);
      }
    });
    console.log(arr);
    return console.log(err);
  }, function(error) {
    return console.log(error.message);
  });

}).call(this);
