// Generated by CoffeeScript 1.9.1
(function() {
  var Q, _, allPromise, collection, p;

  Q = require('q');

  _ = require('underscore');

  p = function(data) {
    return Q.promise(function(resolve, reject) {
      if (data instanceof Object && !(data instanceof Array)) {
        return resolve(data);
      } else {
        return reject(new Error('data is not obj'));
      }
    });
  };

  collection = [
    {
      category: "�ɱȿ�"
    }, {
      category: "����"
    }, {}
  ];

  allPromise = _.map(collection, function(v, i) {
    return p(v);
  });

  Q.any(allPromise).then(function() {
    return console.log('success');
  }, function(error) {
    return console.log(error.message);
  });

}).call(this);
