// Generated by CoffeeScript 1.9.1
(function() {
  var Q, _, test;

  Q = require('q');

  _ = require('underscore');

  test = function() {
    return arguments[0] + arguments[1];
  };

  Q.fcall(test, 1, 2).then(function(result) {
    return console.log(result);
  }, function(error) {
    return console.error(error.message);
  });

}).call(this);
