// Generated by CoffeeScript 1.9.2
(function() {
  var Q, returnValue;

  Q = require('q');

  returnValue = {};

  Q.resolve(returnValue).then(function(v) {
    return console.log(v);
  });

}).call(this);
