// Generated by CoffeeScript 1.9.1
(function() {
  var Q;

  Q = require('q');

  Q.when(1, function(result) {
    return console.log(result);
  }, function(error) {
    return console.log(error);
  });

  Q.fcall(function() {
    return 1;
  }).then(function(result) {
    return console.log(result);
  });

}).call(this);
